/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5i927.Vista;

/**
 *
 * @author josmy
 */
import com.mycompany.parchisc5i927.Controlador.ControladorPrincipal;

public class GUICreditos extends javax.swing.JFrame {

    /**
     * Creates new form GUICreditos
     */
    public GUICreditos(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    
     public void escuchar(ControladorPrincipal controlador){
        btnAtrasCre.addActionListener(controlador);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAtrasCre = new javax.swing.JButton();
        TextCre = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasCre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasCre.setActionCommand("AtrasCreditos");
        btnAtrasCre.setBorderPainted(false);
        btnAtrasCre.setContentAreaFilled(false);
        getContentPane().add(btnAtrasCre, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        TextCre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextCre.setText("DESARROLLADO POR: JOSMY ANTONIO RODRIGUEZ CAMPOS");
        getContentPane().add(TextCre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 530, 170));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroCreditos.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextCre;
    private javax.swing.JButton btnAtrasCre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
