/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5i927.Vista;

/**
 *
 * @author josmy
 */
import com.mycompany.parchisc5i927.Controlador.ControladorPrincipal;
import java.awt.event.ActionListener;

public class GUIHistoria extends javax.swing.JFrame {
    

    /**
     * Creates new form GUIHistoria
     */
    public GUIHistoria(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    
    public void escuchar(ControladorPrincipal controlador){
        btnAtrasHis.addActionListener(controlador);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasHis = new javax.swing.JButton();
        TextHIs = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasHis.setActionCommand("AtrasHistoria");
        btnAtrasHis.setBorderPainted(false);
        btnAtrasHis.setContentAreaFilled(false);
        btnAtrasHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasHisActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        TextHIs.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TextHIs.setText("HISTORIA");
        getContentPane().add(TextHIs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 480, 270));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroHistoria.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasHisActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextHIs;
    private javax.swing.JButton btnAtrasHis;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
