/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5i927.Vista;

import com.mycompany.parchisc5i927.Controlador.ControladorJuego;

/**
 *
 * @author josmy
 */
public class GUIJuego extends javax.swing.JFrame {
    

    /**
     * Creates new form GUIJuego
     */
    public GUIJuego(ControladorJuego controlador) {
        initComponents();
        panelJuego.escuchar(controlador);
        panelControl.escuchar(controlador);    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new com.mycompany.parchisc5i927.Vista.PanelJuego();
        panelControl = new com.mycompany.parchisc5i927.Vista.PanelControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));
        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.parchisc5i927.Vista.PanelControl panelControl;
    private com.mycompany.parchisc5i927.Vista.PanelJuego panelJuego;
    // End of variables declaration//GEN-END:variables
}
