/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5i927.Vista;

import com.mycompany.parchisc5i927.Controlador.ControladorJuego;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author josmy
 */
public class PanelJuego extends javax.swing.JPanel {
    private ImageIcon tableroGrafico;
    private ImageIcon ficha;
    private ControladorJuego controlador;
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        tableroGrafico= new ImageIcon("./src/main/resources/img/tablerografico2.png");
        ficha= new ImageIcon("./src/main/resources/img/pieceblue.png");
    }
    
    public void escuchar(ControladorJuego controlador){
        this.controlador=controlador;
        addMouseListener(controlador);
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        tableroGrafico.paintIcon(this, g, 0, 0);
        ficha.paintIcon(this, g, 453, 468);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroParchisSinBotonesSinLabel.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 680, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
