/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5i927.Vista;

import com.mycompany.parchisc5i927.Controlador.ControladorJuego;

/**
 *
 * @author josmy
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }
    
    public void escuchar(ControladorJuego controlador){
        btnAtrasJuego.addActionListener(controlador);
        btnDado.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnAtrasJuego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setText("DADO");
        btnDado.setActionCommand("Dado");
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        btnAtrasJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasJuego.setActionCommand("AtrasJuego");
        btnAtrasJuego.setContentAreaFilled(false);
        btnAtrasJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasJuegoActionPerformed(evt);
            }
        });
        add(btnAtrasJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroFondo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 928, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDadoActionPerformed

    private void btnAtrasJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasJuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasJuego;
    private javax.swing.JButton btnDado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
